// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_Identifier = {__proto__:null,while:32, if:40, else:42, work:48, error:50, crash:52}
export const parser = LRParser.deserialize({
  version: 14,
  states: ")YQYQPOOObQPO'#C`OgQPO'#C_OlQPO'#C_OOQO'#Cw'#CwQYQPOOOqQPO'#CaOyQPO,58zO!OQPO'#ChO!TQPO,58yOgQPO,58yOOQO-E6u-E6uO!oQPO,58{OOQO1G.f1G.fOOQO,59S,59SO!zQPO'#CjO#RQPO'#CrOOQO'#Ci'#CiO#WQPO'#CiOOQO1G.e1G.eO#oQPO'#CkO#oQPO'#CoO#tQPO'#CsO!TQPO1G.eOOQO'#Cg'#CgO!oQPO'#CgO#yQPO'#CfOOQO'#Cx'#CxO$bQPO'#CeO$vQPO'#CdOOQO'#Cc'#CcOOQO1G.g1G.gOOQO'#C{'#C{O%RQPO,59UOOQO,59U,59UO%YQPO,59^OOQO,59T,59TO%_QPO'#CmO!TQPO,59VO!TQPO,59ZOOQO,59_,59_OOQO7+$P7+$PO%gQPO,59ROOQO'#Cy'#CyO%lQPO,59QOOQO-E6v-E6vO!oQPO'#CzO&TQPO,59OOOQO-E6y-E6yOOQO1G.p1G.pO&`QPO1G.xOOQO'#Cn'#CnO&eQPO,59XOOQO1G.q1G.qO&jQPO1G.uOOQO1G.m1G.mOOQO-E6w-E6wOOQO,59f,59fOOQO-E6x-E6xOOQO7+$d7+$dOOQO1G.s1G.sO!TQPO7+$aOOQO<<G{<<G{",
  stateData: "'a~OrOSPOS~OUQOsPO~OUUO~OuWO~OUYO~Ot[OzTX~Oz]O~Ov^O~OU`O`dOdeOhfOifOjfOsPO{_O~OUhOuiOwhO~O|rO~P!TOusO~OU`O`dOdeOhfOifOjfO{_O~OuuO~O!PxO~Ox{OUYXuYXwYXyYXzYXvYX~OUhOuiOwhOyXXzXXvXX~Oy!OOzWXvWX~O|!RO~P!TOv!SO~O}!TO!O!TO~Ov!XO~Ox{OUYauYawYayYazYavYa~Oy!OOzWavWa~O!P!]O~Ov!^O~Oe!_OUcipcisci`cidcihciicijci{ci|ci~OU~",
  goto: "$epPPPqu!SP!V!Y!`!g!m!s!y#^#^P#j#p#^PP#^#^PPP#s#y$R$X$_TSOTSROT_bX_gqvw!_RVPRo[Qn[RziSm[iR!Z!OXk[il!OXj[il!OQXQRgYQcXSp_qQygQ!VvQ!WwR!`!_^aX_gqvw!_RtbQvdRweR!UuQTORZTUl[i!OR}lQ|jR!Y|Q!PmR![!PQq_R!Qq",
  nodeNames: "⚠ LineComment Program FunctionDeclaration Tag TagContent Identifier Regex Alternation Concatenation Repetition Primary ParameterList Statement Block WhileStatement while Condition ConditionContent IfStatement if else FunctionCall BareStatement work error crash",
  maxTerm: 47,
  skippedNodes: [0,1],
  repeatNodeCount: 5,
  tokenData: "%S~ReXY!dYZ!d]^!dpq!dqr!uuv!zxy#cyz#hz{#m|}#r!O!P#w!]!^#|!^!_$R!`!a$W!a!b$]!c!}$b#R#S$b#T#o$b#o#p$s#p#q$x#q#r$}~!iSr~XY!dYZ!d]^!dpq!d~!zO!O~~#PSP~OY!zZ;'S!z;'S;=`#]<%lO!z~#`P;=`<%l!z~#hOu~~#mOv~~#rOx~~#wOt~~#|Ow~~$RO!P~~$WOs~~$]Oz~~$bO}~~$gSU~!Q![$b!c!}$b#R#S$b#T#o$b~$xO{~~$}Oy~~%SO|~",
  tokenizers: [0],
  topRules: {"Program":[0,2]},
  specialized: [{term: 6, get: (value) => spec_Identifier[value] || -1}],
  tokenPrec: 291
})
